# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GT_to_numeric <- function(vcf_GT, phased = TRUE) {
    .Call(`_LDheatmap_GT_to_numeric`, vcf_GT, phased)
}

